BTCPayServer/Models/ServerViewModels/EmailsViewModel.cs
using BTCPayServer.Services.Mails;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BTCPayServer.Models.ServerViewModels
{
    public class EmailsViewModel
    {
        public string StatusMessage
        {
            get; set;
        }
        public EmailSettings Settings
        {
            get; set;
        }

        [EmailAddress]
        [Display(Name = "Test Email")]
        public string TestEmail
        {
            get; set;
        }
    }
}

BTCPayServer/Models/ServerViewModels/RatesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using BTCPayServer.Services.Rates;

namespace BTCPayServer.Models.ServerViewModels
{
    public class RatesViewModel
    {
        [Display(Name = "Bitcoin average api keys")]
        public string PublicKey { get; set; }
        public string PrivateKey { get; set; }
        [Display(Name = "Cache the rates for ... minutes")]
        [Range(0, 60)]
        public int CacheMinutes { get; set; }
        public GetRateLimitsResponse RateLimits { get; internal set; }
    }
}

BTCPayServer/Models/StoreViewModels/CheckoutExperienceViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using BTCPayServer.Payments;
using BTCPayServer.Services;
using BTCPayServer.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BTCPayServer.Models.StoreViewModels
{
    public class CheckoutExperienceViewModel
    {
        public class Format
        {
            public string Name { get; set; }
            public string Value { get; set; }
            public PaymentMethodId PaymentId { get; set; }
        }
        public SelectList CryptoCurrencies { get; set; }
        public SelectList Languages { get; set; }

        [Display(Name = "Default payment method on checkout")]
        public string DefaultPaymentMethod { get; set; }
        [Display(Name = "Default language on checkout")]
        public string DefaultLang { get; set; }

        [Display(Name = "Link to a custom CSS stylesheet")]
        [Uri]
        public string CustomCSS { get; set; }
        [Display(Name = "Link to a custom logo")]
        [Uri]
        public string CustomLogo { get; set; }

        [Display(Name = "Custom HTML title to display on Checkout page")]
        public string HtmlTitle { get; set; }

        [Display(Name = "Requires a refund email")]
        public bool RequiresRefundEmail { get; set; }

        [Display(Name = "Do not propose on chain payment if the value of the invoice is below...")]
        [MaxLength(20)]
        public string OnChainMinValue { get; set; }

        [Display(Name = "Do not propose lightning payment if value of the invoice is above...")]
        [MaxLength(20)]
        public string LightningMaxValue { get; set; }

        [Display(Name = "Display lightning payment amounts in Satoshis")]
        public bool LightningAmountInSatoshi { get; set; }
        
        [Display(Name = "Redirect invoice to redirect url automatically after paid")]
        public bool  RedirectAutomatically { get; set; }

        public void SetLanguages(LanguageService langService, string defaultLang)
        {
            defaultLang = langService.GetLanguages().Any(language => language.Code == defaultLang) ? defaultLang : "en";
            var choices = langService.GetLanguages().Select(o => new Format() { Name = o.DisplayName, Value = o.Code }).ToArray();
            var chosen = choices.FirstOrDefault(f => f.Value == defaultLang) ?? choices.FirstOrDefault();
            Languages = new SelectList(choices, nameof(chosen.Value), nameof(chosen.Name), chosen);
            DefaultLang = chosen.Value;
        }
    }
}

BTCPayServer/Models/StoreViewModels/PayButtonViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using BTCPayServer.ModelBinders;
using Microsoft.AspNetCore.Mvc;

namespace BTCPayServer.Models.StoreViewModels
{
    public class PayButtonViewModel
    {
        [ModelBinder(BinderType = typeof(InvariantDecimalModelBinder))]
        public decimal Price { get; set; }
        public string InvoiceId { get; set; }
        [Required]
        public string Currency { get; set; }
        public string CheckoutDesc { get; set; }
        public string OrderId { get; set; }
        public int ButtonSize { get; set; }
        public int ButtonType { get; set; }

        // Slider properties (ButtonType = 2)
        public decimal Min { get; set; }
        public decimal Max { get; set; }
        public decimal Step { get; set; }

        // Custom Amount properties (ButtonType = 1)
        public bool SimpleInput { get; set; }
        public bool FitButtonInline { get; set; }

        [Url]
        public string ServerIpn { get; set; }
        [Url]
        public string BrowserRedirect { get; set; }
        [EmailAddress]
        public string NotifyEmail { get; set; }

        public string StoreId { get; set; }
        public string CheckoutQueryString { get; set; }

        // Data that influences Pay Button UI, but not invoice creation
        public string UrlRoot { get; set; }
        public List<string> CurrencyDropdown { get; set; }
        public string PayButtonImageUrl { get; set; }
    }
}

BTCPayServer/Models/StoreViewModels/RatesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using BTCPayServer.Rating;
using BTCPayServer.Services.Rates;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BTCPayServer.Models.StoreViewModels
{
    public class RatesViewModel
    {
        public class TestResultViewModel
        {
            public string CurrencyPair { get; set; }
            public string Rule { get; set; }
            public bool Error { get; set; }
        }
        class Format
        {
            public string Name { get; set; }
            public string Value { get; set; }
            public string Url { get; set; }
        }
        public void SetExchangeRates(CoinAverageExchange[] supportedList, string preferredExchange)
        {
            var defaultStore = preferredExchange ?? CoinAverageRateProvider.CoinAverageName;
            var choices = supportedList.Select(o => new Format() { Name = o.Display, Value = o.Name, Url = o.Url }).ToArray();
            var chosen = choices.FirstOrDefault(f => f.Value == defaultStore) ?? choices.FirstOrDefault();
            Exchanges = new SelectList(choices, nameof(chosen.Value), nameof(chosen.Name), chosen);
            PreferredExchange = chosen.Value;
            RateSource = chosen.Url;
        }

        public List<TestResultViewModel> TestRateRules { get; set; }

        public SelectList Exchanges { get; set; }

        public bool ShowScripting { get; set; }

        [Display(Name = "Rate rules")]
        [MaxLength(2000)]
        public string Script { get; set; }
        public string DefaultScript { get; set; }
        public string ScriptTest { get; set; }
        public string DefaultCurrencyPairs { get; set; }
        public string StoreId { get; set; }
        public CoinAverageExchange[] AvailableExchanges { get; set; }

        [Display(Name = "Add a spread on exchange rate of ... %")]
        [Range(0.0, 100.0)]
        public double Spread
        {
            get;
            set;
        }

        [Display(Name = "Preferred price source (eg. bitfinex, bitstamp...)")]
        public string PreferredExchange { get; set; }

        public string RateSource
        {
            get;
            set;
        }
    }
}

BTCPayServer/Models/StoreViewModels/StoreUsersViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BTCPayServer.Models.StoreViewModels
{
    public class StoreUsersViewModel
    {
        public class StoreUserViewModel
        {
            public string Email { get; set; }
            public string Role { get; set; }
            public string Id { get; set; }
        }
        public StoreUsersViewModel()
        {
            Role = StoreRoles.Guest;
        }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        public string StoreId { get; set; }
        public string Role { get; set; }
        public List<StoreUserViewModel> Users { get; set; }
    }
}

BTCPayServer/Controllers/RateController.cs
using BTCPayServer.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using BTCPayServer.Filters;
using BTCPayServer.Services.Rates;
using BTCPayServer.Services.Stores;
using BTCPayServer.Rating;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
using BTCPayServer.Authentication;
using Microsoft.AspNetCore.Cors;
using System.Threading;
using BTCPayServer.Data;

namespace BTCPayServer.Controllers
{
    [Authorize(AuthenticationSchemes = Security.Policies.BitpayAuthentication)]
    [AllowAnonymous]
    [EnableCors(CorsPolicies.All)]
    public class RateController : Controller
    {
        RateFetcher _RateProviderFactory;
        BTCPayNetworkProvider _NetworkProvider;
        CurrencyNameTable _CurrencyNameTable;
        StoreRepository _StoreRepo;

        public TokenRepository TokenRepository { get; }

        public RateController(
            RateFetcher rateProviderFactory,
            BTCPayNetworkProvider networkProvider,
            TokenRepository tokenRepository,
            StoreRepository storeRepo,
            CurrencyNameTable currencyNameTable)
        {
            _RateProviderFactory = rateProviderFactory ?? throw new ArgumentNullException(nameof(rateProviderFactory));
            _NetworkProvider = networkProvider;
            TokenRepository = tokenRepository;
            _StoreRepo = storeRepo;
            _CurrencyNameTable = currencyNameTable ?? throw new ArgumentNullException(nameof(currencyNameTable));
        }

        [Route("rates/{baseCurrency}")]
        [HttpGet]
        [BitpayAPIConstraint]
        public async Task<IActionResult> GetBaseCurrencyRates(string baseCurrency, string storeId, CancellationToken cancellationToken)
        {
            storeId = await GetStoreId(storeId);
            var store = this.HttpContext.GetStoreData();
            if (store == null || store.Id != storeId)
                store = await _StoreRepo.FindStore(storeId);
            if (store == null)
            {
                var err = Json(new BitpayErrorsModel() { Error = "Store not found" });
                err.StatusCode = 404;
                return err;
            }
            var supportedMethods = store.GetSupportedPaymentMethods(_NetworkProvider);

            var currencyCodes = supportedMethods.Where(method => !string.IsNullOrEmpty(method.PaymentId.CryptoCode))
                .Select(method => method.PaymentId.CryptoCode).Distinct();

            var currencypairs = BuildCurrencyPairs(currencyCodes, baseCurrency);
            
            var result = await GetRates2(currencypairs, store.Id, cancellationToken);
            var rates = (result as JsonResult)?.Value as Rate[];
            if (rates == null)
                return result;
            return Json(new DataWrapper<Rate[]>(rates));
        }


        [Route("rates/{baseCurrency}/{currency}")]
        [HttpGet]
        [BitpayAPIConstraint]
        public async Task<IActionResult> GetCurrencyPairRate(string baseCurrency, string currency, string storeId, CancellationToken cancellationToken)
        {
            storeId = await GetStoreId(storeId);
            var result = await GetRates2($"{baseCurrency}_{currency}", storeId, cancellationToken);
            var rates = (result as JsonResult)?.Value as Rate[];
            if (rates == null)
                return result;
            return Json(new DataWrapper<Rate>(rates.First()));
        }

        [Route("rates")]
        [HttpGet]
        [BitpayAPIConstraint]
        public async Task<IActionResult> GetRates(string currencyPairs, string storeId, CancellationToken cancellationToken)
        {
            var result = await GetRates2(currencyPairs, storeId, cancellationToken);
            var rates = (result as JsonResult)?.Value as Rate[];
            if (rates == null)
                return result;
            return Json(new DataWrapper<Rate[]>(rates));
        }

        private async Task<string> GetStoreId(string storeId)
        {
            if (storeId != null && this.HttpContext.GetStoreData()?.Id == storeId)
                return storeId;
            if(storeId == null)
            {
                var tokens = await this.TokenRepository.GetTokens(this.User.GetSIN());
                storeId = tokens.Select(s => s.StoreId).Where(s => s != null).FirstOrDefault();
            }
            if (storeId == null)
                return null;
            var store = await _StoreRepo.FindStore(storeId);
            if (store == null)
                return null;
            this.HttpContext.SetStoreData(store);
            return storeId;
        }

        [Route("api/rates")]
        [HttpGet]
        public async Task<IActionResult> GetRates2(string currencyPairs, string storeId, CancellationToken cancellationToken)
        {
            storeId = await GetStoreId(storeId);
            if (storeId == null)
            {
                var result = Json(new BitpayErrorsModel() { Error = "You need to specify storeId (in your store settings)" });
                result.StatusCode = 400;
                return result;
            }
            var store = this.HttpContext.GetStoreData();
            if (store == null || store.Id != storeId)
                store = await _StoreRepo.FindStore(storeId);
            if (store == null)
            {
                var result = Json(new BitpayErrorsModel() { Error = "Store not found" });
                result.StatusCode = 404;
                return result;
            }

            if (currencyPairs == null)
            {
                currencyPairs = store.GetStoreBlob().GetDefaultCurrencyPairString();
                if (string.IsNullOrEmpty(currencyPairs))
                {
                    var result = Json(new BitpayErrorsModel() { Error = "You need to setup the default currency pairs in 'Store Settings / Rates' or specify 'currencyPairs' query parameter (eg. BTC_USD,LTC_CAD)." });
                    result.StatusCode = 400;
                    return result;
                }
            }


            var rules = store.GetStoreBlob().GetRateRules(_NetworkProvider);

            HashSet<CurrencyPair> pairs = new HashSet<CurrencyPair>();
            foreach (var currency in currencyPairs.Split(','))
            {
                if (!CurrencyPair.TryParse(currency, out var pair))
                {
                    var result = Json(new BitpayErrorsModel() { Error = $"Currency pair {currency} uncorrectly formatted" });
                    result.StatusCode = 400;
                    return result;
                }
                pairs.Add(pair);
            }

            var fetching = _RateProviderFactory.FetchRates(pairs, rules, cancellationToken);
            await Task.WhenAll(fetching.Select(f => f.Value).ToArray());
            return Json(pairs
                            .Select(r => (Pair: r, Value: fetching[r].GetAwaiter().GetResult().BidAsk?.Bid))
                            .Where(r => r.Value.HasValue)
                            .Select(r =>
                            new Rate()
                            {
                                CryptoCode = r.Pair.Left,
                                Code = r.Pair.Right,
                                CurrencyPair = r.Pair.ToString(),
                                Name = _CurrencyNameTable.GetCurrencyData(r.Pair.Right, true).Name,
                                Value = r.Value.Value
                            }).Where(n => n.Name != null).ToArray());
        }

        private static string BuildCurrencyPairs(IEnumerable<string> currencyCodes, string baseCrypto)
        {
            StringBuilder currencyPairsBuilder = new StringBuilder();
            bool first = true;
            foreach (var currencyCode in currencyCodes)
            {
                if(!first)
                    currencyPairsBuilder.Append(",");
                first = false;
                currencyPairsBuilder.Append($"{baseCrypto}_{currencyCode}");
            }
            return currencyPairsBuilder.ToString();
        }

        public class Rate
        {

            [JsonProperty(PropertyName = "name")]
            public string Name
            {
                get;
                set;
            }
            [JsonProperty(PropertyName = "cryptoCode")]
            public string CryptoCode
            {
                get;
                set;
            }

            [JsonProperty(PropertyName = "currencyPair")]
            public string CurrencyPair
            {
                get;
                set;
            }

            [JsonProperty(PropertyName = "code")]
            public string Code
            {
                get;
                set;
            }
            [JsonProperty(PropertyName = "rate")]
            public decimal Value
            {
                get;
                set;
            }
        }
    }
}

BTCPayServer/Views/Stores/CreateToken.cshtml
@model CreateTokenViewModel
@{
    Layout = "../Shared/_NavLayout.cshtml";
    ViewData.SetActivePageAndTitle(StoreNavPages.Tokens, "Create a new token");
    ViewBag.HidePublicKey = ViewBag.HidePublicKey ?? false;
    ViewBag.ShowStores = ViewBag.ShowStores ?? false;
}


<div class="row">
    <div class="col-md-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="Label"></label>
                @if(ViewBag.HidePublicKey)
                {
                    <small class="text-muted">optional</small>
                }
                <input asp-for="Label" class="form-control" />
                <span asp-validation-for="Label" class="text-danger"></span>
            </div>
            @if(!ViewBag.HidePublicKey)
            {
                <div class="form-group">
                    <label asp-for="PublicKey"></label>
                    <small class="text-muted">Keep empty for server-initiated pairing</small>
                    <input asp-for="PublicKey" class="form-control" />
                    <span asp-validation-for="PublicKey" class="text-danger"></span>
                </div>}

            @if(ViewBag.ShowStores)
            {
                <div class="form-group">
                    <label asp-for="StoreId" class="control-label"></label>
                    <select asp-for="StoreId" asp-items="Model.Stores" class="form-control"></select>
                    <span asp-validation-for="StoreId" class="text-danger"></span>
                </div>}
            else
            {
                <input type="hidden" asp-for="StoreId" />}
            <div class="form-group">
                <input type="submit" value="Request pairing" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

BTCPayServer/Views/Stores/Emails.cshtml
@model BTCPayServer.Models.ServerViewModels.EmailsViewModel
@{
    Layout = "../Shared/_NavLayout.cshtml";
    ViewData.SetActivePageAndTitle(StoreNavPages.Index, "Update Store Email Settings");
}


<partial name="EmailsBody" model="@Model"/>

BTCPayServer/Views/Stores/PayButtonEnable.cshtml
@{
    Layout = "../Shared/_NavLayout.cshtml";
    ViewData.SetActivePageAndTitle(StoreNavPages.PayButton, "Please confirm you want to allow outside world to create invoices in your store (via API).");
    ViewBag.MainTitle = "Pay Button";
}


<div class="row">
    <div class="col-md-10">
        <form method="post">
            <div class="form-group">
                <p>
                    To start using Pay Buttons you need to explicitly turn on this feature.
                    Once you do so, any 3rd party entity will be able to create an invoice on your instance store (via API for example).
                </p>
                @Html.Hidden("EnableStore", true)
                <button name="command" type="submit" value="save" class="btn btn-primary">Allow outside world to create invoices via API (POS app is preauthorised and does not need this enabled).</button>
            </div>
        </form>
    </div>
</div>

BTCPayServer/Views/Stores/Rates.cshtml
@model BTCPayServer.Models.StoreViewModels.RatesViewModel
@{
    Layout = "../Shared/_NavLayout.cshtml";
    ViewData.SetActivePageAndTitle(StoreNavPages.Rates, "Rates");
}

<partial name="_StatusMessage" for="@TempData["TempDataProperty-StatusMessage"]" />

<div class="row">
    <div class="col-md-8">
        <div asp-validation-summary="All" class="text-danger"></div>
    </div>
</div>
<div class="row">
    <div class="col-md-8">
        <form method="post">
            @if (Model.ShowScripting)
            {
                <div class="form-group">
                    <h5>Scripting</h5>
                    <span>Rate script allows you to express precisely how you want to calculate rates for currency pairs.</span>
                    <p class="text-muted">
                        <b>Supported exchanges are</b>:
                        @for (int i = 0; i < Model.AvailableExchanges.Length; i++)
                        {
                            <a href="@Model.AvailableExchanges[i].Url">@Model.AvailableExchanges[i].Name</a><span>@(i == Model.AvailableExchanges.Length - 1 ? "" : ",")</span>
                        }
                    </p>
                    <p><a href="#help" data-toggle="collapse"><b>Click here for more information</b></a></p>
                </div>
            }
            @if (Model.TestRateRules != null)
            {
                <div class="form-group">
                    <h5>Test results:</h5>
                    <table class="table table-sm table-responsive-md">
                        <tbody>
                            @foreach (var result in Model.TestRateRules)
                            {
                                <tr>
                                    @if (result.Error)
                                    {
                                        <th class="small"><span class="fa fa-times" style="color:red;"></span> @result.CurrencyPair</th>
                                    }
                                    else
                                    {
                                        <th class="small"><span class="fa fa-check" style="color:green;"></span> @result.CurrencyPair</th>
                                    }
                                    <td class="small">@result.Rule</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            }
            @if (Model.ShowScripting)
            {
                <div id="help" class="collapse text-left">
                    <p>
                        The script language is composed of several rules composed of a currency pair and a mathematic expression.
                        The example below will use <code>kraken</code> for both <code>LTC_USD</code> and <code>BTC_USD</code> pairs.
                    </p>
                    <pre>
                    <code>
                            LTC_USD = kraken(LTC_USD);
                            BTC_USD = kraken(BTC_USD);
                        </code>
                    </pre>
                    <p>However, explicitely setting specific pairs like this can be a bit difficult. Instead, you can define a rule <code>X_X</code> which will match any currency pair. The following example will use <code>kraken</code> for getting the rate of any currency pair.</p>
                    <pre>
                    <code>
                            X_X = kraken(X_X);
                        </code>
                    </pre>
                    <p>However, <code>kraken</code> does not support the <code>BTC_CAD</code> pair. For this reason you can add a rule mapping all <code>X_CAD</code> to <code>quadrigacx</code>, a Canadian exchange.</p>
                    <pre>
                    <code>
                            X_CAD = quadrigacx(X_CAD);
                            X_X = kraken(X_X);
                        </code>
                    </pre>
                    <p>A given currency pair match the most specific rule. If two rules are matching and are as specific, the first rule will be chosen.</p>
                    <p>
                        But now, what if you want to support <code>DOGE</code>? The problem with <code>DOGE</code> is that most exchange do not have any pair for it. But <code>bittrex</code> has a <code>DOGE_BTC</code> pair. <br />
                        Luckily, the rule engine allow you to reference rules:
                    </p>
                    <pre>
                    <code>
                            DOGE_X = bittrex(DOGE_BTC) * BTC_X
                            X_CAD = quadrigacx(X_CAD);
                            X_X = kraken(X_X);
                        </code>
                    </pre>
                    <p>
                        With <code>DOGE_USD</code> will be expanded to <code>bittrex(DOGE_BTC) * kraken(BTC_USD)</code>. And <code>DOGE_CAD</code> will be expanded to <code>bittrex(DOGE_BTC) * quadrigacx(BTC_CAD)</code>. <br />
                        However, we advise you to write it that way to increase coverage so that <code>DOGE_BTC</code> is also supported:
                    </p>
                    <pre>
                    <code>
                            DOGE_X = DOGE_BTC * BTC_X
                            DOGE_BTC = bittrex(DOGE_BTC)
                            X_CAD = quadrigacx(X_CAD);
                            X_X = kraken(X_X);
                        </code>
                    </pre>
                    <p>
                        It is worth noting that the inverses of those pairs are automatically supported as well.<br />
                        It means that the rule <code>USD_DOGE = 1 / DOGE_USD</code> implicitely exists.
                    </p>

                </div>
                <div class="form-group">
                    <label asp-for="Script"></label>
                    <textarea asp-for="Script" rows="20" cols="80" class="form-control"></textarea>
                    <span asp-validation-for="Script" class="text-danger"></span>
                    <a href="#" onclick="$('#Script').val(defaultScript); return false;">Set to default settings</a>
                </div>
                <div class="form-group">
                    <a asp-action="ShowRateRules" asp-route-scripting="false">Turn off advanced rate rule scripting</a>
                </div>
            }
            else
            {
                <div class="form-group">
                    <label asp-for="PreferredExchange"></label>
                    <select asp-for="PreferredExchange" asp-items="Model.Exchanges" class="form-control"></select>
                    <span asp-validation-for="PreferredExchange" class="text-danger"></span>
                    <p id="PreferredExchangeHelpBlock" class="form-text text-muted">
                        Current price source is <a href="@Model.RateSource" target="_blank">@Model.PreferredExchange</a>.
                    </p>
                </div>
                <div class="form-group">
                    <a asp-action="ShowRateRules" asp-route-scripting="true">Turn on advanced rate rule scripting</a>
                </div>
            }
            <div class="form-group">
                <label asp-for="Spread"></label>
                <div class="input-group">
                    <input asp-for="Spread" class="form-control" />
                    <div class="input-group-prepend">
                        <span class="input-group-text">%</span>
                    </div>
                </div>
                <span asp-validation-for="Spread" class="text-danger"></span>
            </div>
            <div class="form-group">
                <h5>Testing</h5>
                <span>Enter currency pairs which you want to test against your rule (eg. <code>DOGE_USD,DOGE_CAD,BTC_CAD,BTC_USD</code>)</span>
                <div class="input-group">
                    <input placeholder="BTC_USD, BTC_CAD" asp-for="ScriptTest" class="form-control" />
                    <span class="input-group-btn">
                        <button name="command" value="Test" type="submit" class="btn btn-primary" title="Test">
                            <span class="fa fa-vial"></span> Test
                        </button>
                    </span>
                </div>
                <span asp-validation-for="ScriptTest" class="text-danger"></span>
            </div>
            <div class="form-group">
                <h5>Default currency pairs</h5>
                <span>You can query those pairs via REST by querying <a asp-controller="Rate" asp-action="GetRates2" asp-route-storeId="@Model.StoreId" target="_blank">this link</a> without the need to specify currencyPairs.</span>
                <div class="input-group">
                    <input placeholder="BTC_USD, BTC_CAD" asp-for="DefaultCurrencyPairs" class="form-control" />
                </div>
                <span asp-validation-for="DefaultCurrencyPairs" class="text-danger"></span>
            </div>
            <button name="command" type="submit" class="btn btn-primary" value="Save">Save</button>
            <input type="hidden" asp-for="ShowScripting" />
        </form>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">var defaultScript = @Safe.Json(Model.DefaultScript);</script>
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

BTCPayServer/Views/Stores/ShowToken.cshtml
@model BTCPayServer.Authentication.BitTokenEntity
@{
    Layout = "../Shared/_NavLayout.cshtml";
    ViewData.SetActivePageAndTitle(StoreNavPages.Tokens, "Access Tokens");
}

<div class="row">
    <div class="col-md-8">
        <h5>Token information</h5>
        <table class="table table-sm">
            <tr>
                <th>Label</th>
                <td>@Model.Label</td>
            </tr>
            <tr>
                <th>SIN</th>
                <td>@Model.SIN</td>
            </tr>
            <tr>
                <th>Token</th>
                <td>@Model.Value</td>
            </tr>
        </table>
    </div>
</div>